// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw6TXED5XmHTqh8c9nfh3NM3N6grm2DDU',
    appId: '1:343199494461:web:a7313d57403a298bd8d554',
    messagingSenderId: '343199494461',
    projectId: 'chat-app2-842da',
    authDomain: 'chat-app2-842da.firebaseapp.com',
    storageBucket: 'chat-app2-842da.appspot.com',
    measurementId: 'G-0PJLQMH6N7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCscgSTSJXu4ot_d83HBInAdfU5s_yMq7E',
    appId: '1:343199494461:android:ad6367b70a297854d8d554',
    messagingSenderId: '343199494461',
    projectId: 'chat-app2-842da',
    storageBucket: 'chat-app2-842da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALGLgtErPGsnDTx13IZ-Xd4n9bYmcatHg',
    appId: '1:343199494461:ios:9f4412cfeb31ba43d8d554',
    messagingSenderId: '343199494461',
    projectId: 'chat-app2-842da',
    storageBucket: 'chat-app2-842da.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
